// poc/front-end/nextjs/poc/app/register/page.tsx
import Link from "next/link";

export default function Register () {
  return (
    <section className="min-h-screen bg-[url('/BackGround_Rotate.jpg')] bg-cover bg-center flex flex-col items-center justify-center p-10">
      <div className="w-full max-w-sm p-10 bg-white/70 rounded-[45px]">
        <h2 className="text-5xl font-bold mb-8 font-extrabold text-center text-[#F18585] font-[Montserrat]">
            REGISTER
        </h2>
          <input
              type="email"
              placeholder="Email"
              className="w-full mb-6 p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#F18585]"
          />
          <div className="relative mb-4">
              <input
                  placeholder="Password"
                  className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#F18585]"
              />
              <button
                  type="button"
                  className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-500"
              >
              </button>
          </div>
          <Link href={`/isRegisted`}>
            <button
              className="w-full bg-[#F18585] hover:bg-[#e07070] text-white font-extrabold py-3 rounded-lg cursor-pointer"
            >register</button>
          </Link>
        </div>
      </section>
  )
}

// poc/front-end/vuejs/poc/src/views/Register.vue
<template>
  <section class="login-section">
    <div class="login-box">
      <h2 class="register-title">REGISTER</h2>

      <input
        type="email"
        placeholder="Email"
        class="input-field"
      />

      <div class="input-group">
        <input
          type="password"
          placeholder="Password"
          class="input-field"
        />
        <button type="button" class="icon-btn">
        </button>
      </div>

      <RouterLink to="/isRegisted">
        <button class="btn">Register</button>
      </RouterLink>

      <RouterLink to="/login">
        <button class="btn">login</button>
      </RouterLink>
    </div>
  </section>
</template>

<style scoped>
/* Section principale avec fond image */
.login-section {
  min-height: 100vh;
  background: url('/BackGround_Rotate.jpg') center/cover no-repeat;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 40px;
}

/* Box blanche translucide */
.login-box {
  width: 100%;
  max-width: 400px;
  padding: 40px;
  background: rgba(255, 255, 255, 0.7);
  border-radius: 45px;
  display: flex;
  flex-direction: column;
  gap: 20px;
}

/* Titre */
.register-title {
  font-size: 2.5rem;
  font-weight: 800;
  text-align: center;
  margin-bottom: 20px;
  color: #F18585;
  font-family: 'Montserrat', sans-serif;
}

/* Champs */
.input-field {
  width: 100%;
  padding: 12px;
  border: 1px solid #d1d5db; /* gris clair */
  border-radius: 8px;
  font-size: 1rem;
}
.input-field:focus {
  outline: none;
  border-color: #F18585;
  box-shadow: 0 0 0 2px rgba(241, 133, 133, 0.5);
}

/* Group input + bouton (ex: œil pour mot de passe) */
.input-group {
  position: relative;
}
.icon-btn {
  position: absolute;
  right: 12px;
  top: 50%;
  transform: translateY(-50%);
  background: transparent;
  border: none;
  cursor: pointer;
  color: #6b7280; /* gris */
}

/* Boutons */
.btn {
  width: 100%;
  padding: 12px;
  border: none;
  border-radius: 8px;
  font-weight: 800;
  color: white;
  background-color: #F18585;
  cursor: pointer;
  transition: background-color 0.2s;
  margin-top: 10px;
}
.btn:hover {
  background-color: #e07070;
}
</style>
